/*
 * Go-coding API
 *
 * Go-coding API Gateway.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: jason.zhuy@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// APIError is a standard error object returned by all API calls
type ApiError struct {

	// APIInfo describes API path and version.
	ApiInfo string `json:"apiInfo,omitempty"`

	// Code is an integer HTTP status code.
	Code int32 `json:"code"`

	// CodeStatus is an HTTP status.
	CodeStatus string `json:"codeStatus,omitempty"`

	// Message defines a message associated with the error.
	Message string `json:"message"`

	// Log is additional error information, e.g. log entries, stack trace, etc.
	Log string `json:"log,omitempty"`
}
