/*
 * Go-coding API
 *
 * Go-coding API Gateway.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: jason.zhuy@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

import (
	"time"
)

// User defines a user information.
type User struct {

	// ID is a user identifier
	Id int32 `json:"id,omitempty"`

	// Active indicates if the user is active.
	Active bool `json:"active,omitempty"`

	// Alias is user name alias.
	Alias string `json:"alias,omitempty"`

	// APIKey is user API key for service requests.
	ApiKey string `json:"apiKey,omitempty"`

	// Password stores hashed user password.
	Password string `json:"password,omitempty"`

	// EmailAddress is a user email address.
	EmailAddress string `json:"emailAddress,omitempty"`

	// FirstName is a user's first name.
	FirstName string `json:"firstName,omitempty"`

	// LastName is a user's last name.
	LastName string `json:"lastName,omitempty"`

	// DefaultRole is default role name.
	DefaultRole string `json:"defaultRole,omitempty"`

	// SystemUID is a system user id.
	SystemUid int32 `json:"systemUid,omitempty"`

	// Created is the date/time of the user beinng created.
	Created time.Time `json:"created,omitempty"`

	// LastLoginDateTime is the date/time of the user last login.
	LastLoginDateTime time.Time `json:"lastLoginDateTime,omitempty"`

	// LastSessionID is the last login session identifier.
	LastSessionId int32 `json:"lastSessionId,omitempty"`
}
