go:
  math:
    maxInt8: 127
    minInt8: -128
    maxUint8: 255
    maxInt16: 32767
    minInt16: -32768
    maxUint16: 65535
    maxInt32: 2147483647
    minInt32: -2147483648
    maxUint32: 4294967295
    maxInt64: 9223372036854775807
    minInt64: -9223372036854775808
    maxUint64: 18446744073709551615

goobar:
  api_key: SOCKEYE_API_KEY
  api_url: https://sockeye/api
  encrypted_api_key: AQICAHg3HNyIwRj/VgA+LeTSbBvD+KLqwR4I7fTUIoefURORLQF4TeZG1NW7J1fYok4dBM83AAAAYjBgBgkqhkiG9w0BBwagUzBRAgEAMEwGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMW7xGM12GTODwP4JRAgEQgB+Aq191ktDJAFXQrJASRNm8oj4q21rYVlj6OkOOhoaz
  bool_tests:
    - False
    - True
    - false
    - true
    - FALSE
    - TRUE
    - disabled
    - ENABLED
    - Disabled
    - enabled
    - TurnOff
    - On
    - off
    - on
    - No
    - Yes
    - 0
    - 1
  data:
    threat_class: ThreatClass
    threat_family: ThreatFamily
    threat_source: ThreatSource

test:
  nil:

xxdb:
  debug: True
  database: sockeye
  host: 127.0.0.1
  port: 3306
  username: admin
  password: pass
